apiVersion: apps/v1
kind: Deployment
metadata:
  name: ralphserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ralphserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ralphserver
    spec:
      containers:
      - image: ralvarez1/webserver:v3.0
        name: ralphserver
        ports:
        - containerPort: 5000
          name: ralphserver
